# Generated by Django 5.0.6 on 2024-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_management', '0003_alter_patient_allergies_alter_patient_histories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
